2024-07-05 19:41:00,013 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-07-05 19:41:00,014 - INFO - [33mPress CTRL+C to quit[0m
2024-07-05 19:41:06,320 - INFO - 127.0.0.1 - - [05/Jul/2024 19:41:06] "[33mGET / HTTP/1.1[0m" 404 -
2024-07-05 19:42:03,668 - INFO - 127.0.0.1 - - [05/Jul/2024 19:42:03] "[33mGET /api/vms HTTP/1.1[0m" 404 -
2024-07-05 19:42:05,382 - INFO - 127.0.0.1 - - [05/Jul/2024 19:42:05] "[33mGET /api/vms HTTP/1.1[0m" 404 -
2024-07-05 19:45:47,761 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6000
 * Running on http://192.168.111.142:6000
2024-07-05 19:45:47,762 - INFO - [33mPress CTRL+C to quit[0m
2024-07-05 19:51:30,137 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:6000
 * Running on http://192.168.111.142:6000
2024-07-05 19:51:30,137 - INFO - [33mPress CTRL+C to quit[0m
2024-07-05 19:56:45,475 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-05 20:00:32,534 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-05 20:08:56,664 - INFO - Request data: {'command': 'get_snapshots', 'name': 'alma'}
2024-07-05 20:10:14,700 - INFO - Request data: {'command': 'get_snapshots', 'name': 'alma'}
2024-07-05 20:10:38,680 - INFO - Request data: {'command': 'get_snapshots', 'name': 'ubuntu'}
2024-07-05 20:41:11,849 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2024-07-05 20:41:11,849 - INFO - [33mPress CTRL+C to quit[0m
2024-07-05 20:41:16,571 - INFO - 127.0.0.1 - - [05/Jul/2024 20:41:16] "GET / HTTP/1.1" 200 -
2024-07-05 20:41:16,626 - INFO - 127.0.0.1 - - [05/Jul/2024 20:41:16] "[33mGET /static/js/main.c3ffcb1e.js HTTP/1.1[0m" 404 -
2024-07-05 20:41:16,673 - INFO - 127.0.0.1 - - [05/Jul/2024 20:41:16] "[33mGET /static/css/main.e6c4a01d.css HTTP/1.1[0m" 404 -
2024-07-05 20:41:17,196 - INFO - 127.0.0.1 - - [05/Jul/2024 20:41:17] "[33mGET /manifest.json HTTP/1.1[0m" 404 -
2024-07-05 20:41:24,335 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-05 20:41:24,336 - INFO - 127.0.0.1 - - [05/Jul/2024 20:41:24] "GET /list_vms HTTP/1.1" 200 -
2024-07-05 20:41:54,548 - INFO - 127.0.0.1 - - [05/Jul/2024 20:41:54] "[33mGET /manifest.json HTTP/1.1[0m" 404 -
2024-07-05 20:42:01,440 - INFO - 127.0.0.1 - - [05/Jul/2024 20:42:01] "[33mGET /api/vms HTTP/1.1[0m" 404 -
2024-07-05 20:42:11,489 - INFO - 127.0.0.1 - - [05/Jul/2024 20:42:11] "[33mGET /vms HTTP/1.1[0m" 404 -
2024-07-05 20:42:43,391 - INFO - 127.0.0.1 - - [05/Jul/2024 20:42:43] "[36mGET / HTTP/1.1[0m" 304 -
2024-07-05 20:42:43,487 - INFO - 127.0.0.1 - - [05/Jul/2024 20:42:43] "[33mGET /static/js/main.c3ffcb1e.js HTTP/1.1[0m" 404 -
2024-07-05 20:42:43,570 - INFO - 127.0.0.1 - - [05/Jul/2024 20:42:43] "[33mGET /static/css/main.e6c4a01d.css HTTP/1.1[0m" 404 -
2024-07-05 20:42:44,128 - INFO - 127.0.0.1 - - [05/Jul/2024 20:42:44] "[33mGET /manifest.json HTTP/1.1[0m" 404 -
2024-07-05 20:54:07,815 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-05 20:56:39,427 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("mindex.html", s=s)
NameError: name 's' is not defined
2024-07-05 20:57:23,553 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("mindex.html", s=s)
NameError: name 's' is not defined
2024-07-05 20:58:25,365 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("mindex.html", s=s)
NameError: name 's' is not defined
2024-07-05 20:58:52,583 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("mindex.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:04:07,776 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:04:15,411 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:04:41,163 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:04:44,852 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:04:45,859 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:04:57,647 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:05:38,996 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:05:41,082 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-05 21:05:57,710 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 25, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-06 01:07:21,069 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 23, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-06 01:08:24,298 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 23, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-06 01:08:25,506 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 23, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-06 01:09:00,320 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 23, in serve_index
    return  render_template("index.html", s=s)
NameError: name 's' is not defined
2024-07-06 01:09:56,596 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-06 01:14:49,153 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-06 01:14:50,239 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-06 01:15:13,831 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 28, in serve_index
    return  render_template("index.html")
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2024-07-06 01:18:05,627 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 28, in serve_index
    return  render_template("index.html")
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2024-07-06 01:18:07,303 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 28, in serve_index
    return  render_template("index.html")
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2024-07-06 01:22:22,740 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/a/sock_clint/./main.py", line 28, in serve_index
    return  render_template("index.html")
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2024-07-06 01:22:36,159 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-06 02:03:29,195 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.111.142:5000
2024-07-06 02:03:29,195 - INFO - [33mPress CTRL+C to quit[0m
2024-07-06 02:03:44,758 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:03:44] code 400, message Bad request syntax ('\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03%rxS\x15=#"zk?6\x93Z\x8a¥Ø')
2024-07-06 02:03:44,758 - INFO - 192.168.113.251 - - [06/Jul/2024 02:03:44] "[35m[1m\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03%rxS\x15=#"zk?6\x93Z\x8a¥Ø[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:03:44,761 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:03:44] code 400, message Bad request version ('QÊ\x11E\x96e®gëR\x0eñ\x13')
2024-07-06 02:03:44,761 - INFO - 192.168.113.251 - - [06/Jul/2024 02:03:44] "[35m[1m\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03\x06ù×p°Sì\x7fgÖË\x9c¶\x0bÍâ\x97Kt\x93àÚÄç\x9cÕ¢;«Ê¨5 \x16¾©fÝS£\x8d\x9bÂ¯×.KûÆ\x02\x1a\x8d?y\x96\x97yD¯©ár²x\x93\x00 zz\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06SÚÚ\x00\x00þ\x0d\x00Ú\x00\x00\x01\x00\x01Ô\x00 \x18\x9fä\x13UvØ8vÉTµO±þ{%ä,o~2\x9b\x03>Ë\x9a¤Ü\x10Ò^\x00°Nô1\x90¸'\x07-øC\x87øDb@\x80*q\x1d¼Ð¶¦=ÑºÉ`y\x9d\x86\x15ÉÖClôÔ®*w(6b\x84°6¢Þ\x93}\x92\x98¬¿*\x8f¤çæºåÅ¤ÿ,Ü²´¹ì¥\x95|\x12«7\x85QÊ\x11E\x96e®gëR\x0eñ\x13[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:03:44,798 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:03:44] code 400, message Bad request version ('%ª¿')
2024-07-06 02:03:44,799 - INFO - 192.168.113.251 - - [06/Jul/2024 02:03:44] "[35m[1m\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03£cí4J¥O£.Ò½×_·óNA¾q9\x9bh!\x95?AÜäüS¹d 0³jÉCFÔæL\x9cv ß³\x17|\x13\x1d õ\x85õJË3¡9Ä\x96ÖA¾\x00 jj\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06Sêê\x00\x00þ\x0d\x00Ú\x00\x00\x01\x00\x01\x90\x00 %ª¿[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:03:44,800 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:03:44] code 400, message Bad request version ('\x00\x02\x01\x00\x00')
2024-07-06 02:03:44,802 - INFO - 192.168.113.251 - - [06/Jul/2024 02:03:44] "[35m[1m\x16\x03\x01\x07\x00\x01\x00\x06ü\x03\x03\x0f-/¼©\x84\x07Ó\x15ÜàÜîÍKß=\x89irsìm\x1b<4´"\x0e\x1c\x85ú c¢ \x0c8Þ\x95*Hø\x05JNý©è]Ü\x028)\x87\x19#Ú('LÑÙ7!\x00 \x8a\x8a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93\x9a\x9a\x00\x00\x00\x0b\x00\x02\x01\x00\x00[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:03:52,655 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "main.py", line 28, in serve_index
    return  render_template("index.html")
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2024-07-06 02:03:52,664 - INFO - 192.168.113.251 - - [06/Jul/2024 02:03:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-07-06 02:03:53,677 - INFO - 192.168.113.251 - - [06/Jul/2024 02:03:53] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2024-07-06 02:04:20,286 - ERROR - Socket error: [Errno 111] Connection refused
2024-07-06 02:04:20,288 - INFO - 192.168.113.251 - - [06/Jul/2024 02:04:20] "GET /list_vms HTTP/1.1" 200 -
2024-07-06 02:04:39,518 - INFO - 192.168.113.251 - - [06/Jul/2024 02:04:39] "[33mGET /api HTTP/1.1[0m" 404 -
2024-07-06 02:04:47,037 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "main.py", line 28, in serve_index
    return  render_template("index.html")
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2024-07-06 02:04:47,040 - INFO - 192.168.113.251 - - [06/Jul/2024 02:04:47] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-07-06 02:09:01,733 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.111.142:5000
2024-07-06 02:09:01,733 - INFO - [33mPress CTRL+C to quit[0m
2024-07-06 02:09:06,054 - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask_cors/extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "main.py", line 28, in serve_index
    return  render_template("index.html")
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
  File "/home/a/sock_clint/env/lib/python3.8/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.html
2024-07-06 02:09:06,068 - INFO - 192.168.113.251 - - [06/Jul/2024 02:09:06] "[35m[1mGET / HTTP/1.1[0m" 500 -
2024-07-06 02:10:08,158 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.111.142:5000
2024-07-06 02:10:08,159 - INFO - [33mPress CTRL+C to quit[0m
2024-07-06 02:24:52,367 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.111.142:5000
2024-07-06 02:24:52,367 - INFO - [33mPress CTRL+C to quit[0m
2024-07-06 02:25:21,823 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.111.142:5000
2024-07-06 02:25:21,823 - INFO - [33mPress CTRL+C to quit[0m
2024-07-06 02:26:16,027 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.111.142:5000
2024-07-06 02:26:16,027 - INFO - [33mPress CTRL+C to quit[0m
2024-07-06 02:26:25,288 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:26:25] code 400, message Bad request version ('\x8a\x8a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93êê\x00\x00\x00')
2024-07-06 02:26:25,289 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:26:25] code 400, message Bad request version ('**\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x063JJ\x00\x00\x00')
2024-07-06 02:26:25,289 - INFO - 192.168.113.251 - - [06/Jul/2024 02:26:25] "[35m[1m\x16\x03\x01\x07\x00\x01\x00\x06ü\x03\x03l8:³6çÐ)\x18Nsô\x03£äÉ.%3}¤ º\x10\x96à¦4IdW  µûd\x17«¾Æ\x912ê\x1fÂ-r\x1f>#®3h0\x7fÇ¦\x10\x9d\x9aûÂëÈ\x97\x00 \x8a\x8a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93êê\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:26:25,290 - INFO - 192.168.113.251 - - [06/Jul/2024 02:26:25] "[35m[1m\x16\x03\x01\x06 \x01\x00\x06\x9c\x03\x03KÈ\x97s\x1c¿Íu{nÕ¨\x1bd\x9aùÒÚ)\x9bËèoÓLùò\x7fG\x86%Y dÌ}\x06Êf\x0b`\x97ÿZI\x97eÙÂ\x17\x8cíé§\x16®Ò\x8b\x91¸¨XÎ.\x86\x00 **\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x063JJ\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:26:25,334 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:26:25] code 400, message Bad request version ('ïT')
2024-07-06 02:26:25,335 - INFO - 192.168.113.251 - - [06/Jul/2024 02:26:25] "[35m[1m\x16\x03\x01\x06À\x01\x00\x06¼\x03\x03Çñ\x80y,\x0e@à^K¡\x9epéï\x94\x97¿öB\x99Òñìé$r\x9cùb·ß ÏÒQ2\x90ÍCmYHfÐX[\x1au\x89Â°È6x~D\x1a±Ï\x8d¡®\x00%\x00 êê\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06S::\x00\x00\x00\x12\x00\x00\x00\x05\x00\x05\x01\x00\x00\x00\x00\x00#\x00\x00\x00\x0b\x00\x02\x01\x00\x00\x17\x00\x00\x00+\x00\x07\x06JJ\x03\x04\x03\x03þ\x0d\x00Ú\x00\x00\x01\x00\x01­\x00 H\x9cxìt\x1cU\x93l¼\x91Ã\x87ÈiôÒG\x88\x82l\x7fááª>\x19UQ\x11\x97 \x00°\x1dún\x1deë\x1e'ßs®\x91QÜ\x85:\x0cô\x04æ\x06[\x04\x00¼è[Z¢Òò\x96£­t^7\x8be\\ÒÜ)óõZ½\x9e\x90£Æz\x03\x05xü\x04aV.hiú\x8amd}\x12\x9fPnÉg\x05øÉ>Ú/,\x9b\x1dïT[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:26:25,336 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:26:25] code 400, message Bad request version ('¡\x026àÑ')
2024-07-06 02:26:25,336 - INFO - 192.168.113.251 - - [06/Jul/2024 02:26:25] "[35m[1m\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03(\x13ß_Ûâàñ\x86\x1cù\x1c¡\x026àÑ[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:28:04,432 - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.111.142:5000
2024-07-06 02:28:04,433 - INFO - [33mPress CTRL+C to quit[0m
2024-07-06 02:28:11,555 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:28:11] code 400, message Bad request version ('\x98wÉH\x9a\x9a¦\x08}\x93¶Û\x14ý\x87bNõ×P\x98x?¢Â\x1a')
2024-07-06 02:28:11,556 - INFO - 192.168.113.251 - - [06/Jul/2024 02:28:11] "[35m[1m\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03Þ\x8cM\x06Z|¥ØS\x11îYá°áÓRzÝ~ÛOz½É¨\x93ÉáÙÙÂ êÉãìÅeÎ+]fÿ\x0eÁ\x06\x02ñ\x101¸çå\x08,\x90XñO,\x18&\x95Ð\x00 JJ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06s**\x00\x00\x00-\x00\x02\x01\x01\x00\x10\x00\x0e\x00\x0c\x02h2\x08http/1.1\x00+\x00\x07\x06úú\x03\x04\x03\x03þ\x0d\x00ú\x00\x00\x01\x00\x01Ä\x00 \x98wÉH\x9a\x9a¦\x08}\x93¶Û\x14ý\x87bNõ×P\x98x?¢Â\x1a[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:28:11,558 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:28:11] code 400, message Bad request version ("\x00\x02\x01\x00\x003\x04ï\x04íjj\x00\x01\x00c\x99\x04ÀoÆ'\x8c\x17¦¦\x19\x84¡\x84zV\x89Ôí¿&R")
2024-07-06 02:28:11,559 - INFO - 192.168.113.251 - - [06/Jul/2024 02:28:11] "[35m[1m\x16\x03\x01\x07\x00\x01\x00\x06ü\x03\x03¬{\x90ß^\\YhÉ\x85dI'%×RP\x9fÜ¨\x9c\x93G»\x81"¹Å£É\x07è xd6\x1a|\x9crìFª\x03Êð\x06\x105\x11\x83ÚÀ\x00ó§ðQã\x11Ûë¨Ö\x05\x00 \x8a\x8a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06\x93zz\x00\x00\x00-\x00\x02\x01\x01\x00\x12\x00\x00\x00+\x00\x07\x06zz\x03\x04\x03\x03\x00\x0b\x00\x02\x01\x00\x003\x04ï\x04íjj\x00\x01\x00c\x99\x04ÀoÆ'\x8c\x17¦¦\x19\x84¡\x84zV\x89Ôí¿&R[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:28:11,598 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:28:11] code 400, message Bad request version ('\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00+\x00\x07\x06êê\x03\x04\x03\x03\x00\x1b\x00\x03\x02\x00\x02\x00#\x00\x00\x00')
2024-07-06 02:28:11,599 - INFO - 192.168.113.251 - - [06/Jul/2024 02:28:11] "[35m[1m\x16\x03\x01\x06 \x01\x00\x06\x9c\x03\x03t\x97¸E\x91é-ü¬mToUCþ:i\x92\x04(a×·B\x99\x1c=²:\x1fQÚ &ï\x8c«Î¤¶$Ô3É0¿\x14½\x96Ý\x8b`\x1cñ¶®â\x86øk½\x1f.\\£\x00 ªª\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x063\x9a\x9a\x00\x00\x00\x17\x00\x00\x00\x0d\x00\x12\x00\x10\x04\x03\x08\x04\x04\x01\x05\x03\x08\x05\x05\x01\x08\x06\x06\x01\x00+\x00\x07\x06êê\x03\x04\x03\x03\x00\x1b\x00\x03\x02\x00\x02\x00#\x00\x00\x00[0m" HTTPStatus.BAD_REQUEST -
2024-07-06 02:28:11,601 - ERROR - 192.168.113.251 - - [06/Jul/2024 02:28:11] code 400, message Bad request version ('\x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06s')
2024-07-06 02:28:11,602 - INFO - 192.168.113.251 - - [06/Jul/2024 02:28:11] "[35m[1m\x16\x03\x01\x06à\x01\x00\x06Ü\x03\x03¥÷¶ÉÒº\x078µ\x14èl\x1em\x0cI\x9dz\x13\x0b\x8f\x02Ñú1nyL\x87k~G \x9a¢²\x9c\x11ÑÓ\x9e\x12±\x90 öNîn\x0cèc\x97\x0e4Ø5u¿×\x950¨ò\x97\x00 \x9a\x9a\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x01\x00\x06s[0m" HTTPStatus.BAD_REQUEST -
